# Generated by Django 3.2.8 on 2021-10-31 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20211031_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant_Approved_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landlord_name', models.TextField(default='')),
                ('house', models.TextField()),
                ('street', models.TextField()),
                ('landmark', models.TextField()),
                ('locality', models.TextField()),
                ('vtc', models.TextField()),
                ('subdist', models.TextField()),
                ('district', models.TextField()),
                ('state', models.TextField()),
                ('country', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
